services:
  mysql:
    image: mysql:8.0
    container_name: lms_mysql
    command: --default-time-zone=+07:00
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: lms_mvp
      MYSQL_USER: lms
      MYSQL_PASSWORD: lms123
    ports:
      - "3307:3306"
    volumes:
      - lms_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-prootpass"]
      interval: 5s
      timeout: 3s
      retries: 30

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: lms_pma
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpass
    ports:
      - "8081:80"

volumes:
  lms_mysql_data:
